#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
    echo "This script must run as root."
    exit 1
fi

# Stop containers first to release file locks
# --volumes flag removes named volumes defined in compose (grafana_storage)
docker compose down --volumes

# Remove filesystem artifacts generated by setup script
rm -rf .influxdb3
rm -f .env
rm -f influxdb3-explorer/config/config.json
rm -f grafana/provisioning/datasources/datasources.yaml

echo "Environment hard reset complete."
docker ps --all